version: '3'

services:
  prometheus-sanduba:
    container_name: prometheus-sanduba
    image: prom/prometheus:v2.30.0
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/config:/etc/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
    networks:
      - sanduba-network
  
  grafana-sanduba:
    container_name: grafana-sanduba
    image: grafana/grafana:8.1.5
    hostname: grafana
    environment:
      -  GF_SECURITY_ADMIN_PASSWORD=admin
    ports:
      - 3000:3000
    depends_on:
      - prometheus-sanduba
    networks:
      - sanduba-network

  nfs-sanduba:
    container_name: nfs-sanduba
    image: itsthenetwork/nfs-server-alpine:12
    restart: unless-stopped
    privileged: true
    environment:
      - SHARED_DIRECTORY=/data
    volumes:
      - /data/nfs-storage:/data
    ports:
      - 2049:2049

  database-sanduba:
    container_name: database-sanduba
    hostname: database-sanduba
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      MSSQL_SA_PASSWORD: "P@ssW0rd!"
      ACCEPT_EULA: "Y"
    ports:
      - 1433:1433
    networks:
      - sanduba-network

  api-sanduba:
    container_name: restaurantesanduba.api
    hostname: restaurantesanduba.api
    image: cangelosilima/restaurantesanduba.api:latest
    environment:
      ASPNETCORE_URLS: "http://+:9000"
    ports:
      - 5161:9000
    depends_on:
      - database-sanduba
      - grafana-sanduba
      - prometheus-sanduba
    networks:
      - sanduba-network

networks:
   sanduba-network:
       driver: bridge