version: '3'

services:
  prometheus-sanduba:
    container_name: prometheus-sanduba
    image: prom/prometheus:v2.30.0
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/config:/etc/prometheus
      - ./prometheus/data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
  
  grafana-sanduba:
    container_name: grafana-sanduba
    image: grafana/grafana:8.1.5
    hostname: grafana
    environment:
      -  GF_SECURITY_ADMIN_PASSWORD=admin
    ports:
      - 3000:3000
    depends_on:
      - prometheus-sanduba

  mssql-sanduba:
    container_name: mssql-sanduba
    image: mcr.microsoft.com/mssql/server:latest
    environment:
      SA_PASSWORD: "P@ssW0rd!"
      ACCEPT_EULA: "Y"
    ports:
      - 1433:1433

  api-sanduba:
    build:
      context: ../api/RestauranteSanduba
      dockerfile: ../RestauranteSanduba/src/adapter/driver/API/Dockerfile
    image: restaurantesanduba.api
    container_name: restaurantesanduba.api
    hostname: api
    ports:
      - 5161:80
    depends_on:
      - mssql-sanduba
      - grafana-sanduba
      - prometheus-sanduba