apiVersion: v1
kind: Pod
metadata:
  name: sanduba-api-pod
  labels:
    app: sanduba-api-pod
spec:
  containers:
    - name: restaurantesanduba-pod-api
      image: cangelosilima/restaurantesanduba.api:latest
      ports: 
        - containerPort: 9000
      env:
        - name: ASPNETCORE_URLS
          valueFrom:
            configMapKeyRef:
              name: api-config
              key: ASPNETCORE_URLS
        - name: ASPNETCORE_ConnectionStrings__DefaultConnection
          valueFrom:
            configMapKeyRef:
              name: db-config
              key: CONNECTION_STRING
              
      resources:
        limits:
          cpu: "0.5"
          memory: "512Mi"
        requests:
          cpu: "0.2"
          memory: "256Mi" 