apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sanduba-db-pvc
  labels: 
    name: sanduba-db-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: local-storage-db