apiVersion: v1
kind: PersistentVolume
metadata:
  name: sanduba-volume
  labels:
    disk: sanduba-volume
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: local-storage-db
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /data/shared
  # mountOptions:
  #   - hard
  #   - nfsvers=4.1
  # nfs:
  #   path: /data/nfs-storage
  #   server: 10.10.10.69
