apiVersion: v1
kind: PersistentVolume
metadata:
  name: sanduba-volume
  labels:
    disk: sanduba-volume
    app: sanduba
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: local-storage-db
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /data/shared