name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file api/RestauranteSanduba/src/api/Dockerfile --tag docker push cangelosilima/restaurantesanduba.api:2023-12-15.01:$(date +%s)
